version: '3.8'

services:
  # PHP and Apache service
  web:
    container_name: olxpricetracker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Map port 80 in the container to port 8080 on the host
    volumes:
      - .:/var/www/html # Mount the current directory to /var/www/html in the container
    networks:
      - app-network
    depends_on:
      - db # Ensure db service is started before web service

  # MySQL service
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql # Persist data between container restarts
    networks:
      - app-network

#  test_db:
#    image: mysql:5.7
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_TEST_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_TEST_DATABASE}
#      MYSQL_USER: ${MYSQL_TEST_USER}
#      MYSQL_PASSWORD: ${MYSQL_TEST_PASSWORD}
#    volumes:
#      - test_db_data:/var/lib/mysql
#    networks:
#      - app-network

  # PHPMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80" # Map port 80 in the container to port 8081 on the host
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    networks:
      - app-network
    depends_on:
      - db # Ensure db service is started before phpmyadmin service

# Define networks
networks:
  app-network:
    driver: bridge

# Define volumes
volumes:
  db_data:
